### ISSUE TITLE
Tutorial reorg for 2.0b

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#1072]
- [x] Bring tutorials and teaching tutorials into v2_dev (and ensure they pass ci) @mcflugen is currently working on this at #1071 
- [x] Configure binder for this repo (happening on #1071 as well)
- [x] Reorganize notebook folder within Landlab to have a less flat structure (happening on #1071 as well)

- [x] Put a warning on these two repositories that these repositories are no longer being maintained and that the content is hosted elsewhere. 

- [x] Revise RST page on tutorials to just point to welcome.ipynb and to include a download .tar of just the notebooks folder.
- [x] Update docs to point to new binder instance (correct file AND landlab/landlab/release)
- [x] Update links to binder to point to THIS repo instead of tutorials repo.

**Comment by kbarnhart** [comment]
lasts bits done in a forthcoming PR
